### PR TITLE
Provenance updates

### PR DESCRIPTION
**Pull request by kasei**
The major changes in this PR:

* Improve stability of UUIDs across pipeline runs
* Improve performance of pipeline
* Bugfixes and modeling improvements to address reported issues:
  * Fixes (or confirmed as fixed previously): DEV-2275, DEV-2178, DEV-2064, DEV-2063,DEV-2297, DEV-2361, DEV-2285
  * Partially addresses issues raised in DEV-1555, DEV-2482, DEV-2432

### CODE REVIEW

**Comment by azaroth42** [comment]
Reasonable skim looks good.

**Comment by kasei** [comment]
OK. Some of this is conditional on responses from GRI, so I'll hold off on merging for now.

**Comment by kasei** [comment]
@azaroth42 I think this needs merging before it gets any bigger. If it's OK with you, I'm comfortable moving forward under the assumption that GRI will accept our proposed change that bases identifiers on `pi_record_no` and `catalog_number`, and also ignores authority names with brackets in them. We can roll these changes back in the future if that turns out not to be acceptable.

**Comment by azaroth42** [comment]
Yup, merge away.

**Pull request merged**
